languageCode = "pl"
title = "Daj Znak"
theme = "hugo-cards"
enableRobotsTXT = true
DefaultContentLanguage = "pl"

[languages]
  [languages.pl]
    weight = 1
    title = "Daj znak!"
    [languages.pl.params]
        defaultImage = "frankfurt-2020-simple.svg"
    [languages.pl.params.navigation]
	about = "Nasza inicjatywa"
	contact = "Daj nam znak"
  [languages.de]
    weight = 2
    title = "Daj znak!"
    [languages.de.params]
        defaultImage = "frankfurt-2020-simple.svg"
    [languages.de.params.navigation]
